version: "3.9"
services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "8086:8086"
    restart: always

  conf:
    build:
      context: .
      dockerfile: Dockerfile.conf
