FROM busybox

RUN wget --quiet https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.7-linux-amd64.tar.gz && \
    tar -xvf influxdb2-2.0.7-linux-amd64.tar.gz influxdb2-2.0.7-linux-amd64/influxd --strip-components 1 -C /bin && \
    rm influxdb2-2.0.7-linux-amd64.tar.gz

ENTRYPOINT ["influxd"]
